version: '3'

services:

  mongo:
    container_name: unicorns_mongodb
    image: mongo
    ports:
      - 27017:27017
    networks:
      - backend

  api:
    build: .
    container_name: unicorns_api
    depends_on:
      - mongo
    ports:
      - 3333:3333
    volumes:
      - ./:/usr/src/app
    networks:
      - backend

networks:
  backend:
